### ISSUE TITLE
Change broadcast pattern to unicast pattern

### ISSUE THREAD

**Issue by hanghoo** [brianmc95/OpenCV2X#16]
Hello, hope you are well. I hope to consult you on how could I change the broadcast to the unicast pattern. I cannot find an obvious place for this configuration.

I got the broadcast information from the paper "OpenCV2X Mode 4 A Simulation Extension for Cellular Vehicular Communication Networks"

Thank you for your help and thanks in advance.

**Comment by brianmc95** [comment]
Hi Hanghoo,

I am closing this issue as you reached out to me through email and we worked through the issue there.

Kind Regards,
Brian
