### ISSUE TITLE
No rule to make target 'run_simulte-cars'.  Stop.

### ISSUE THREAD

**Issue by divakar5** [brianmc95/OpenCV2X#20]
Hi Sir,

I'm facing the some issue while triggering "cmake --build build --target run_simulte-cars". I didn't understand the solutions you have posted in earlier closed issue. I tried the first solution by changing Config highwayFast to Config Base but still the same issue. could you please tell me how to overcome this issue? your help will be much appreciated.
![Opencv2x simulation error](https://user-images.githubusercontent.com/80413167/111189225-e1f20a00-85db-11eb-9c35-aa6d957f2008.PNG)

**Comment by brianmc95** [comment]
Hi @divakar5, 

I don't believe that is actually your issue it looks as though you haven't built the project correctly in some way are you sure you have setup the project correclty? Documentation to do so is available [here](http://www.cs.ucc.ie/cv2x/media/OpenCV2X_Documentation.pdf). It should not be the case that the target isn't available altogether, if the issue were the configuration it would at least build and start running omnet++ not crash instantly.

Let me know maybe just check the build directory and see if the outcome of calling `cmake ..` and `cmake --build .`

Kind Regards,
Brian

**Comment by divakar5** [comment]
Hi Sir,

I have followed the instruction given in the document to build the OpenCV2X project. And initially, I faced some build issues which I corrected and the build passed using  cmake .. and cmake --build .
one observation I would like to tell is when I did a git clone of OpenCV2X from Github the "Inet, simulte, veins, vanetza" present in extern folders were empty, hence I used "git clone --recurse-submodule https://github.com/brianmc95/OpenCV2X.git"  this fetched the Extern folders correctly.

Apart from this I believe I did build the project correctly if you want me to delete the OpenCV2X folder and again fetch from repo build from initial I would like to try out this as well since all the requirements are already installed.

Thanks and regards
Divakar R

**Comment by brianmc95** [comment]
Hi Divakar,

Yes when you clone you need to pull the additional projects, I assume you also built these in turn i.e. ran `make vanetza` `make inet` and `make simulte` as well as `cd extern/veins & ./configure & make`

The only additional step after this is to ensure that the `WITH_SIMULTE` flag is set to true in the cmake configuration, by going to the `build` folder and running `ccmake .` and ensure the above variable is set to On. Other than this I can't see why the target would be missing.

**Comment by divakar5** [comment]
Hi Sir,

The issue got resolved! Thank you. 
I was able to run the "cmake --build build --target run_simulte-cars" and the simulation result appeared on the Terminal window, I have attached the pic below. Is there any option to view the simulation using Qtenv or SUMO or any GUI for MAP with Highway scenario?
![Opencv2x simulation result](https://user-images.githubusercontent.com/80413167/111433335-2b4d7100-8724-11eb-9988-a22d9efdd079.PNG)

**Comment by brianmc95** [comment]
Hi @divakar5,

Glad it is up and running. So for SUMO you need to update the `omnetpp.ini` file with the following line `*.traci.launcher.sumo = "sumo-gui"` this will launch sumo when the experiments starts.

Otherwise to get QTenv then you need to again update cmake, so go into your build directory and using `ccmake` or whatever mechanism you have you can update the `OMNETPP_RUN_ENV` from `Cmdenv` to `Qtenv`

That should get it working.

**Comment by divakar5** [comment]
Hi Sir,

Thanks for the information, it works now, I simulated the HighwayFast scenario and generated the plot for that and attached the picture here. I also simulated highwaySlow but I didn't see difference between their Config's in Omnetpp.ini. Could you please suggest me where should I look to understand about these scenarios better? And how the integration of SImulte is done in your project with respect to Artery? which Files i need to focus so I can have better understanding of whole scenarios of Integration as well as simulation.
Thanks a lot for your valuable guidance!
![highwayFast](https://user-images.githubusercontent.com/80413167/111775265-89ba5100-88d6-11eb-8d93-6960ded7e6b6.PNG)

**Comment by brianmc95** [comment]
Hi @divakar5,

Glad you have it up and running to be honest while my original paper is old and the result out dated at this point due to several changes in the model it still provides a very detailed explanation of how the model works and is a good starting point for explaining what you need to look into. It is available through IEEE at this [link](https://ieeexplore.ieee.org/document/8858436) I'd recommend you go through this. 

I'm going to close this issue now but feel free to fire on questions to my email.
