### ISSUE TITLE
Documentation link permissions

### ISSUE THREAD

**Issue by maxwellmcmanus** [brianmc95/OpenCV2X#31]
Hi, I am trying to access the documentation via the link provided in the README file, but I receive "Error 403: Forbidden" and cannot access the resource. 

How are permissions granted for this documentation? Or instead, is there another place I can find documentation for this program? 

Thank you in advance for your help!

**Comment by xxxxxy211** [comment]
i encoutered the same question.

**Comment by xxxxxy211** [comment]
i find the solution. all the docs can find in the web https://github.com/brianmc95/cv2x.git
